package com.foulatah.foulatah.navigation

const val ROUTE_LOGIN = "login"
const val ROUTE_UPDATE_BILLS = "update_bills"
const val ROUTE_VIEW_TENANTS = "view_tenants"
const val ROUTE_HOME = "home"
const val ROUTE_ABOUT = "about"
const val ROUTE_ADD_TENANTS = "add_tenants"
const val ROUTE_SPLASH = "splash"
const val ROUTE_REGISTER = "register"
const val ROUTE_DASHBOARD = "dashboard"
const val ROUTE_VIEW_BILLS = "view_bills"
const val ROUTE_COMPLAINTS = "complaints"
const val ROUTE_SUGGESTIONS = "suggestions"
const val ROUTE_PAYMENT = "payment"